### ISSUE TITLE
statemind audit checklist

### ISSUE THREAD

**Issue by banteg** [yearn/veYFI#175]
- [x] C1 veYFI balance might not decrease https://github.com/yearn/veYFI/pull/179
- [x] C2 Incorrect balance calculation leading to higher reward https://github.com/yearn/veYFI/pull/182
- [x] H1 Incorrect interface _fixed_
- [x] H2 Incorrect balance calculation https://github.com/yearn/veYFI/pull/182
- [x] M1 Tokens may be lost if checkpoint functions are not called for 20 weeks https://github.com/yearn/veYFI/pull/188
- [x] I1 Incorrect comment https://github.com/yearn/veYFI/pull/189
- [x] I2 Unclear naming of function burn 🤷‍♂️
- [x] I3 Unused arguments https://github.com/yearn/veYFI/blob/master/contracts/RewardPool.vy#L128
- [x] I4 Function _find_timestamp_epoch() can be view https://github.com/yearn/veYFI/pull/190
- [x] I5 Code duplication removed: https://github.com/yearn/veYFI/pull/182/files#diff-e19e2a3b7ea177b93f0db8b5dd2287b47ffa2c55d69e1155b789d9f43060369aL145
- [x] I6 Excess reentrancy protection (should just ack and keep protection, no harm)
- [x] I7 No check for address zero (ack. yearn thinks this issue can be mitigated during proper ops deployment of contract risk and impact are low since if address are not configured contract can be redeployed)
- [x] I8 Unnecessary condition (ack)
- [x] I9 Unreachable code (ack)
- [x] I10 Unnecessary gas usage https://github.com/yearn/veYFI/pull/193

**Comment by storming0x** [comment]
Can we get the commit hash of H1 fixed for tracking?

**Comment by storming0x** [comment]
i ticked this one 

> - [ ] I2 Unclear naming of function burn 🤷‍♂️ 

We should just ack this one and move on
