### ISSUE TITLE
chainsecurity audit checklist

### ISSUE THREAD

**Issue by banteg** [yearn/veYFI#176]
Critical Severity:
  - [x] 5.1 End Slope Changes Not Set https://github.com/yearn/veYFI/pull/179
  - [x] 5.2 Incorrect Interface Definition and Calls to veYFI in RewardPool __fixed__
  - [x] 5.3 Kink Timestamp Can Be Set to a Past Timestamp https://github.com/yearn/veYFI/pull/179
  - [x] 5.4 getPriorVotes Does Not Replay Slope Changes https://github.com/yearn/veYFI/pull/182

High Severity:
- [x] 5.6 Kink Timestamps Are Too Early https://github.com/yearn/veYFI/pull/179/files#diff-6fd160f92367bb0a82b8e6175db39d65a4d7e52e47a340ec0b637afe49078317R68
- [x] 5.7 RewardPool Calculates Incorrect Balances https://github.com/yearn/veYFI/pull/182

Medium Severity:
- [x] 5.8 Rewards can become unclaimable https://github.com/yearn/veYFI/pull/188

Low Severity:
- [x] 5.9 Incorrect Natspec https://github.com/yearn/veYFI/pull/191
- [x] 5.10 Long Locks Lead to Incorrect Balances (documented in) -> https://github.com/yearn/veYFI/pull/191
- [x] 5.11 Unspecified Behavior in Balance Functions https://github.com/yearn/veYFI/pull/192
- [x] 5.14 Missing explicit view decorator in function https://github.com/yearn/veYFI/pull/190

**Comment by storming0x** [comment]
Can we get commit hash added to 5.2 and 5.5 for fixed issue tracking
